spring:
  profiles:
    active: YfDev1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leon
    username: root
    password: 123456

test:
  condition : test.true
  name : test.yangfei
  password : test.123456
  age : 37