# 启动变量配置 spring.profiles.active=prod
# 配置启动项目后可以使用此文件内容
# 配置值与文件-后的参数一致，如application-prod.properties，配置参数为prod

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leon
    username: root
    password: 123456

test:
  condition : test.true
  name : test.yangfei
  password : test.123456
  age : 37

yf:
  name: yangfeiprod
  password: 123456prod